package ReverseApp;

/**
* ReverseApp/ReverseIntfHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./ReverseIntf.idl
* Tuesday, 23 April, 2024 9:27:01 PM IST
*/

public final class ReverseIntfHolder implements org.omg.CORBA.portable.Streamable
{
  public ReverseApp.ReverseIntf value = null;

  public ReverseIntfHolder ()
  {
  }

  public ReverseIntfHolder (ReverseApp.ReverseIntf initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = ReverseApp.ReverseIntfHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    ReverseApp.ReverseIntfHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return ReverseApp.ReverseIntfHelper.type ();
  }

}
