package ReverseApp;


/**
* ReverseApp/ReverseIntfHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./ReverseIntf.idl
* Tuesday, 23 April, 2024 9:27:01 PM IST
*/

abstract public class ReverseIntfHelper
{
  private static String  _id = "IDL:ReverseApp/ReverseIntf:1.0";

  public static void insert (org.omg.CORBA.Any a, ReverseApp.ReverseIntf that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static ReverseApp.ReverseIntf extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (ReverseApp.ReverseIntfHelper.id (), "ReverseIntf");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static ReverseApp.ReverseIntf read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_ReverseIntfStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, ReverseApp.ReverseIntf value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static ReverseApp.ReverseIntf narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof ReverseApp.ReverseIntf)
      return (ReverseApp.ReverseIntf)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      ReverseApp._ReverseIntfStub stub = new ReverseApp._ReverseIntfStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static ReverseApp.ReverseIntf unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof ReverseApp.ReverseIntf)
      return (ReverseApp.ReverseIntf)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      ReverseApp._ReverseIntfStub stub = new ReverseApp._ReverseIntfStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
