package ReverseApp;


/**
* ReverseApp/ReverseIntf.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./ReverseIntf.idl
* Tuesday, 23 April, 2024 9:27:01 PM IST
*/

public interface ReverseIntf extends ReverseIntfOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface ReverseIntf
