package ReverseApp;


/**
* ReverseApp/ReverseIntfOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./ReverseIntf.idl
* Tuesday, 23 April, 2024 9:27:01 PM IST
*/

public interface ReverseIntfOperations 
{
  String getReverseString (String str1);
  int getReverseNumber (int num1);
  void shutdown ();
} // interface ReverseIntfOperations
